spring.datasource:
  url: jdbc:mysql://localhost:3306/bloglib?useSSL = false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 12345
spring.jpa:
  hibernate.ddl-auto: validate
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: false
  properties.hibernate.jdbc.time_zone: UTC
spring.liquibase.enabled: false
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: justtestit11@gmail.com
  password: _testit123
  properties.mail.smtp:
    auth: true
    starttls.enable: true
upload.path: /blogDev/uploads



blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7(903)666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005
